name: Python PR check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # Specify your desired Python version

    #- name: Install dependencies
     # run: pip install -r requirements.txt # If you have a requirements.txt file

    - name: Print Demo Python Formatter
      run: echo "Demo Python Formatter from GitHub Actions!" 
      
    #Install the python package Black and runs the python formatter on the files
    - name: Install Black
      run: pip install black
    - name: Run Black formatter
      run: black src/*.py

    # Auto commit to the branch with formating  
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Format Python code with Black"
        branch: ${{ github.head_ref || github.ref_name }}

    # Create a Pull request with formatted Changes, someone manully approve it
    - name: Create Pull Request with formatted changes (optional)
      if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "chore: format Python code with Black"
        branch: ${{ github.head_ref }}
        push_options: "--force-with-lease"
